steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/Dockerfile.audio
      - -t
      - europe-west4-docker.pkg.dev/senior-design-488908/lectureai-repo/audio-worker:latest
      - .
images:
  - europe-west4-docker.pkg.dev/senior-design-488908/lectureai-repo/audio-worker:latest
