services:
  lectureai-api:
    build: .
    container_name: lectureai_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./core/storage:/app/core/storage
    restart: always

  lectureai-worker:
    build: .
    container_name: lectureai_worker
    command: python core/pipelines/pubsub_listener.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./core/storage:/app/core/storage
    restart: always
